APP_NAME="mini-RAG"
APP_VERSION="0.1"
OPENAI_API_KEY=""

FILE_ALLOWED_TYPES=["text/plain", "application/pdf"]
FILE_MAX_SIZE=10
FILE_DEFAULT_CHUNK_SIZE=512000 #512KB


POSTGRES_USERNAME="postgres"
POSTGRES_PASSWORD="postgres_password"
POSTGRES_HOST="postgres"
POSTGRES_PORT=5432
POSTGRES_MAIN_DATABASE="minirag"

#========================== LLM Config =========================
OPENAI_API_KEY =""
COHERE_API_KEY =""

BASE_URL = ""

GENERATION_BACKEND_LITERAL = ["OPENAI","COHERE"]
GENERATION_BACKEND = ""

EMBEDDING_BACKEND_LITERAL = ["OPENAI","COHERE"]
EMBEDDING_BACKEND = ""


GENERATION_MODEL_ID_LITERAL = ["gpt-4o","cohere/cohere-command-a","aya:latest"]
GENERATION_MODEL_ID =""

EMBEDDING_MODEL_ID_LITERAL = ["text-embedding-3-small","Cohere-embed-v3-multilingual"]
EMBEDDING_MODEL_ID =""
EMBEDDING_MODEL_SIZE =

INPUT_DEFAULT_MAX_CHARACTERS=1024
GENERATION_DEFAULT_MAX_TOKENS=200
GENERATION_DEFAULT_TEMPERATURE=0.1

#========================== Vector DB Config =========================
VECTOR_DB_BACKEND_LITERAL = ["QDRANT","PGVECTOR"]
VECTOR_DB_BACKEND = "QDRANT"
VECTOR_DB_PATH = "qdrant_db"
VECTOR_DB_DISTANCE_METHOD = "cosine"
VECTOR_DB_PGVEC_INDEX_THRESHOLD = 100

#========================== Template Config =========================
PRIMARY_LAN = "en"
DEFAULT_LANG = "en"

